### ISSUE TITLE
Which ECMAScript specification version should be implemented?

### ISSUE THREAD

**Issue by britzke** [britzke/rennspur#11]
ECMAScript specification is actually released in version 7.0. It must be examined, which version of ECMAScript specification should be used for the implementations here.

**Comment by seka94** [comment]
http://kangax.github.io/compat-table/es5/
I suggest version 5.

**Comment by britzke** [comment]
ES5 is from 2009/2011. That is a long time. ES6 provides many language feature, which would help us to be more productive. Our code would be more intuitive, too. Please check, if it is possible to work with ES6, regardless of the incompatibility of the Android 5.1 browser.

**Comment by britzke** [comment]
All major web browsers support several ES6 features like class, array functions, etc.
It would be nice, to have a list of supported features, in order to be able to consistently use them here.

**Comment by LeoWinterDE** [comment]
We are using ES6, probably no support for Android 5.1, iOS 9, IE 11, SF 9, FF 45 and every older browser version - closing #11
