### ISSUE TITLE
I18n for admin interface

### ISSUE THREAD

**Issue by britzke** [britzke/rennspur#35]
The admin interface must be prepared to be internationalised. The first thee languages could be English, German, and Turkish. The selection of the various languages should be made automatically  depending on the browser language settings.
A good starting point for I18N with JSF could be http://courses.coreservlets.com/Course-Materials/pdf/jsf/jsf2/JSF2-Properties-Files.pdf

**Comment by CapslockIsOn** [comment]
Dublicate #36

**Comment by britzke** [comment]
The original issue should be left open and the duplicate should be closed. (Closes #36)

**Comment by britzke** [comment]
It would be better, if the 'trans' is called 'translation'.

**Comment by britzke** [comment]
Polish language files should also be added by @K-Ivancea.

**Comment by britzke** [comment]
Nearly all strings are i18n-ized. Further translations will be made for the issues where they arise.
