### ISSUE TITLE
Map should be embeddable and configurable

### ISSUE THREAD

**Issue by britzke** [britzke/rennspur#37]
The map for the front-end has several configuration needs. For this reason it is necessary, to make the front-end code configurable either by constructor parameter or by global variables. The code should be embeddable on every website by a website administrator with intermediate skills.
It would be convenient to use code like this for embedding:
```html
<link rel="stylesheet" href="/rennspur/webjars/openlayers/3.20.0/ol.css" type="text/css">
<link rel="stylesheet" href="/rennspur/rs.css" type="text/css">
<script src="/rennspur/webjars/jquery/3.1.1-1/jquery.min.js" type="application/ecmascript"></script>
<script src="/rennspur/webjars/openlayers/3.20.0/ol.js" type="application/ecmascript"></script>
<script src="/rennspur/rs.js" type="text/ecmascript"></script>
...
<script type="application/ecmascript">
// configuration options
// map creation
</script>
...
<div id="rs-map"/>
...

**Comment by maXLeev** [comment]
Configurable should be the following points:
- constructor
- events
- server
- port
- context route

**Comment by britzke** [comment]
I think, all of the parameters should be wether configurable by constructor or variables, which are assigned before the constructor is called. That implicates a Jason object (e. g. {property:"value1, ...}).
Following parameters seems to be needed:
- racing event
- domain of the server
- port
- context root/servlet-mapping/service-url
May be there are other parameters, which are needed to be configured.

**Comment by britzke** [comment]
A `rsMap` can now be configured by using a properties object as a parameter e. g. 
``` javascript
var map = new rs.Map( {
			div : "rs-map",
			theme : "terrain",
			center : [13.03434,54.33432]
});
```
