### ISSUE TITLE
persistence.xml must be deployed with maven built war

### ISSUE THREAD

**Issue by britzke** [britzke/rennspur#42]
When doing a maven build with goal "package", the file persistence.xml must be deployed correctly.

**Comment by britzke** [comment]
@kbalt and @Erothh : can you please confirm, that the persistence.xml is now packed to the right place via maven build and that the war is deployable?

**Comment by LeoWinterDE** [comment]
Running maven with `package clean install -DskipTests -Denvironment=prod` provides me with a running product .war file and a persistence.xml in the right place. Without `-Denvironment=prod` it's the default development environment.

So yes it's in the right place.
